# Usar a imagem oficial do Node.js LTS
FROM node:18

# Criar o diretório de trabalho dentro do container
WORKDIR /app

# Copiar os arquivos package.json e package-lock.json
COPY package*.json ./

# Instalar as dependências do projeto
RUN npm install

# Copiar todo o restante do código para o container
COPY . .

# Expor a porta que o servidor Node.js vai usar
EXPOSE 3000

# Comando para iniciar o servidor Node.js
CMD ["npm", "start"]
